/**
 * tg-bot - Telegram bot for system administration
 * cmd_control.h - System control command handlers (/reboot)
 * MIT License - Copyright (c) 2026
 */

#ifndef CMD_CONTROL_H
#define CMD_CONTROL_H

#include "commands.h"

// ============================================================================
// PUBLIC API (V2 HANDLERS)
// ============================================================================

/**
 * Request system reboot (generates confirmation token)
 * 
 * This is a two-step process for safety:
 *   1. /reboot           - Generates and returns a 6-digit confirmation token
 *   2. /reboot_confirm   - Validates token and executes reboot
 * 
 * Tokens are stateless, derived from chat_id and current time.
 * TTL is configurable via security_set_token_ttl().
 * 
 * @param ctx  Command context
 * @return     0 on success, -1 on error
 */
int cmd_reboot_v2(command_ctx_t *ctx);

/**
 * Confirm and execute system reboot
 * 
 * Validates the provided token against the one generated by /reboot.
 * On success, triggers reboot via lifecycle_request_shutdown().
 * 
 * Token validation includes:
 *   - Format check (6-digit integer)
 *   - Time window check (within TTL)
 *   - Bruteforce protection (blocks after 5 failures)
 *   - Replay protection (single-use)
 * 
 * @param ctx  Command context (args contains token)
 * @return     0 on success, -1 on error
 */
int cmd_reboot_confirm_v2(command_ctx_t *ctx);

#endif // CMD_CONTROL_H
