/**
 * tg-bot - Telegram bot for system administration
 * cmd_control.h - System control command handlers (/reboot, /restart, /totp_setup)
 * MIT License - Copyright (c) 2026 ironmist45
 */

#ifndef CMD_CONTROL_H
#define CMD_CONTROL_H

#include "commands.h"

// ============================================================================
// PUBLIC API (V2 HANDLERS)
// ============================================================================

/**
 * Request system reboot (generates confirmation token)
 *
 * This is a two-step process for safety:
 *   1. /reboot           - Generates and returns a 6-digit confirmation token
 *   2. /reboot_confirm   - Validates token and executes reboot
 *
 * Tokens are stateless, derived from chat_id and current time.
 * TTL is configurable via security_set_token_ttl().
 *
 * @param ctx  Command context
 * @return     0 on success, -1 on error
 */
int cmd_reboot_v2(command_ctx_t *ctx);

/**
 * Confirm and execute system reboot
 *
 * Validates the provided token against the one generated by /reboot.
 * On success, triggers reboot via lifecycle_request_shutdown().
 *
 * Token validation includes:
 *   - Format check (6-digit integer)
 *   - Time window check (within TTL)
 *   - Bruteforce protection (blocks after 5 failures)
 *   - Replay protection (single-use)
 *
 * @param ctx  Command context (args contains token)
 * @return     0 on success, -1 on error
 */
int cmd_reboot_confirm_v2(command_ctx_t *ctx);

/**
 * Request bot restart (generates confirmation token)
 *
 * This is a two-step process for safety:
 *   1. /restart           - Generates and returns a 6-digit confirmation token
 *   2. /restart_confirm   - Validates token and executes restart
 *
 * Unlike /reboot, this only restarts the bot process via
 * systemctl restart tg-bot — the server itself is not affected.
 *
 * Tokens are stateless, derived from chat_id and current time.
 * TTL is configurable via security_set_token_ttl().
 *
 * @param ctx  Command context
 * @return     0 on success, -1 on error
 */
int cmd_restart_v2(command_ctx_t *ctx);

/**
 * Confirm and execute bot restart
 *
 * Validates the provided token against the one generated by /restart.
 * On success, triggers restart via lifecycle_request_shutdown().
 *
 * Token validation includes:
 *   - Format check (6-digit integer)
 *   - Time window check (within TTL)
 *   - Bruteforce protection (blocks after 5 failures)
 *   - Replay protection (single-use)
 *
 * @param ctx  Command context (args contains token)
 * @return     0 on success, -1 on error
 */
int cmd_restart_confirm_v2(command_ctx_t *ctx);

/**
 * Show TOTP setup information
 *
 * If TOTP_SECRET is configured in the config file, displays:
 *   - The base32-encoded secret
 *   - An otpauth:// URI ready to import into Aegis, Google Authenticator,
 *     Authy, or any RFC 6238 compatible application
 *
 * If TOTP_SECRET is not configured, explains how to set it up.
 *
 * This command does NOT require confirmation — it would be circular
 * to require TOTP in order to set up TOTP.
 *
 * @param ctx  Command context
 * @return     0 on success, -1 on error
 */
int cmd_totp_setup_v2(command_ctx_t *ctx);

#endif /* CMD_CONTROL_H */
