/**
 * tg-bot - Telegram bot for system administration
 * cmd_control.h - System control command handlers (/reboot)
 * MIT License - Copyright (c) 2026
 */

#ifndef CMD_CONTROL_H
#define CMD_CONTROL_H

#include <stddef.h>
#include "commands.h"

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Request system reboot (generates confirmation token)
 * 
 * This is a two-step process for safety:
 *   1. /reboot           - Generates and returns a 6-digit confirmation token
 *   2. /reboot_confirm   - Validates token and executes reboot
 * 
 * Tokens are stateless, derived from chat_id and current time.
 * TTL is configurable via security_set_token_ttl().
 * 
 * @param argc       Argument count
 * @param argv       Argument vector
 * @param chat_id    Chat ID of requester
 * @param response   Response buffer
 * @param resp_size  Size of response buffer
 * @param resp_type  Output: response type (always RESP_MARKDOWN)
 * @return           0 on success, -1 on error
 */
int cmd_reboot(int argc, char *argv[],
               long chat_id,
               char *response,
               size_t resp_size,
               response_type_t *resp_type);

/**
 * Confirm and execute system reboot
 * 
 * Validates the provided token against the one generated by /reboot.
 * On success, triggers reboot via lifecycle_request_shutdown().
 * 
 * Token validation includes:
 *   - Format check (6-digit integer)
 *   - Time window check (within TTL)
 *   - Bruteforce protection (blocks after 5 failures)
 *   - Replay protection (single-use)
 * 
 * @param argc       Argument count (must be >= 2)
 * @param argv       Argument vector (argv[1] = token)
 * @param chat_id    Chat ID of requester
 * @param response   Response buffer
 * @param resp_size  Size of response buffer
 * @param resp_type  Output: response type (always RESP_MARKDOWN)
 * @return           0 on success, -1 on error
 */
int cmd_reboot_confirm(int argc, char *argv[],
                       long chat_id,
                       char *response,
                       size_t resp_size,
                       response_type_t *resp_type);

#endif // CMD_CONTROL_H
